Rails 6.1 fix for "remove_index"
This was causing an error like:

    ArgumentError: You must specify the index name

When running "rails db:migrate:down" on a migration like:

    add_index :users, :email, unique: true