Disable idempotent module and fix Rails 6.1 compat issue (#1)
Update configs for our own testing

- Ruby 3.0.2
- Postgres 11 (via Docker)

Skip tests that are failing on master

Disable idempotent module

Skip tests instead of commenting them out

To make future rebases easier

Remove unnecessary test change

Rails 6.1 fix for "remove_index"

This was causing an error like:

    ArgumentError: You must specify the index name

When running "rails db:migrate:down" on a migration like:

    add_index :users, :email, unique: true